# Generated by Django 2.1.4 on 2019-01-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_text_bold',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='arcane_dust_gained',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_class',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_race',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_rarity',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_set',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_text',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='craftingcost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='flavor_text',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='mana',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
