# Generated by Django 2.1.4 on 2019-01-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hs_game', '0002_auto_20190112_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_text_bold',
        ),
    ]
