# Generated by Django 2.1.4 on 2019-01-12 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs_game', '0003_remove_card_card_text_bold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card_race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card_rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='card_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_game.Card_class'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_game.Card_race'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_rarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_game.Card_rarity'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_game.Card_set'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_game.Card_type'),
        ),
    ]
