# Generated by Django 2.1.4 on 2019-01-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_game', '0004_auto_20190112_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_text',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='flavor_text',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
