# Generated by Django 2.1.4 on 2019-01-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hs_game', '0005_auto_20190112_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_game.Card_class'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_game.Card_race'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_rarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_game.Card_rarity'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_game.Card_set'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_game.Card_type'),
        ),
    ]
