# Generated by Django 2.1.4 on 2019-01-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_game', '0006_auto_20190112_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/cards'),
        ),
    ]
