# Generated by Django 2.1.4 on 2019-01-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
        ('hs_game', '0007_auto_20190112_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(verbose_name=1)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='cards', to='authenticate.UserProfile'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='static/images/cards'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hs_game.Card'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.UserProfile'),
        ),
        migrations.AddField(
            model_name='deck',
            name='card',
            field=models.ManyToManyField(blank=True, related_name='decks', to='hs_game.Card'),
        ),
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='authenticate.UserProfile'),
        ),
    ]
