# Generated by Django 2.1.4 on 2019-01-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_game', '0008_auto_20190119_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='static/assets/images/cards'),
        ),
    ]
