# Generated by Django 2.1.4 on 2019-01-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_game', '0009_auto_20190121_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='cards', to='authenticate.UserProfile'),
        ),
    ]
