# Generated by Django 2.1.4 on 2019-01-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hs_game', '0011_auto_20190121_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='cards'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
