# Generated by Django 2.1.4 on 2019-01-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_userprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
